CREATE TABLE AVIONES_COMBATE (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100),
    PAIS        VARCHAR2(100),
    TIPO        VARCHAR2(100),
    VELOCIDAD   VARCHAR2(50),
    IMAGEN      BLOB
);
COMMIT;
--
DROP DIRECTORY IMG_DIR;
CREATE DIRECTORY IMG_DIR AS 'C:\oracle_images';
--GRANT READ ON DIRECTORY IMG_DIR TO SYSTEM;
--
INSERT INTO AVIONES_COMBATE (NOMBRE, PAIS, TIPO, VELOCIDAD, IMAGEN)
VALUES ('F-16 Fighting Falcon', 'Estados Unidos', 'Caza multirrol', 'Mach 2.0', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'F-22 Raptor', 'Estados Unidos', 'Caza furtivo', 'Mach 2.25', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'F-35 Lightning II', 'Estados Unidos', 'Caza furtivo multirrol', 'Mach 1.6', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'Su-57', 'Rusia', 'Caza furtivo', 'Mach 2.0', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'Eurofighter Typhoon', 'Europa', 'Caza multirrol', 'Mach 2.0', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'Dassault Rafale', 'Francia', 'Caza multirrol', 'Mach 1.8', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'MiG-29', 'Rusia', 'Caza de superioridad aérea', 'Mach 2.25', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'JAS 39 Gripen', 'Suecia', 'Caza ligero', 'Mach 2.0', EMPTY_BLOB());

INSERT INTO AVIONES_COMBATE VALUES (DEFAULT, 'Chengdu J-20', 'China', 'Caza furtivo', 'Mach 2.0', EMPTY_BLOB());

COMMIT;
--
SELECT * FROM AVIONES_COMBATE;
--
SELECT * FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME = 'IMG_DIR';
--
DECLARE
  v_file BFILE;
BEGIN
  v_file := BFILENAME('IMG_DIR', 'f16.jpg');
  DBMS_LOB.FILEOPEN(v_file, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.FILECLOSE(v_file);
END;
/
--
DECLARE
    v_blob  BLOB;
    v_file  BFILE;
BEGIN
    FOR r IN (
        SELECT NOMBRE,
               CASE NOMBRE
                   WHEN 'F-16 Fighting Falcon' THEN 'f16.jpg'
                   WHEN 'F-22 Raptor' THEN 'f22.jpg'
                   WHEN 'F-35 Lightning II' THEN 'f35.jpg'
                   WHEN 'Su-57' THEN 'Su-57.jpg'
                   WHEN 'Eurofighter Typhoon' THEN 'eurofighter.jpg'
                   WHEN 'Dassault Rafale' THEN 'rafale.jpg'
                   WHEN 'MiG-29' THEN 'mig29.jpg'
                   WHEN 'JAS 39 Gripen' THEN 'gripen.jpg'
                   WHEN 'Chengdu J-20' THEN 'j20.jpg'
               END AS FILE_NAME
        FROM AVIONES_COMBATE
    ) LOOP
        SELECT IMAGEN
        INTO v_blob
        FROM AVIONES_COMBATE
        WHERE NOMBRE = r.NOMBRE
        FOR UPDATE;

        v_file := BFILENAME('IMG_DIR', r.FILE_NAME);

        DBMS_LOB.FILEOPEN(v_file, DBMS_LOB.FILE_READONLY);
        DBMS_LOB.LOADFROMFILE(
            v_blob,
            v_file,
            DBMS_LOB.GETLENGTH(v_file)
        );
        DBMS_LOB.FILECLOSE(v_file);
    END LOOP;

    COMMIT;
END;
/

COMMIT;
--
SELECT * FROM AVIONES_COMBATE;